**Available Methods**

/historical/wikipedia/{ticker}  
* Returns historical weekly Wikipedia pageviews for the given ticker

/live/wikipedia  
* Returns last week's Wikipedia pageview for every company

#### Imports

In [8]:
import pandas as pd
import numpy as np
import requests
import quiverquant

## Using QuiverQuant's API to Access Data

In [4]:
parser = ConfigParser()
_ = parser.read('notebook.cfg')
quant_auth_key = parser.get('my_api', 'quant_key')
url = "https://api.quiverquant.com/beta/historical/wikipedia/FB"
headers = {'accept': 'application/json',
'X-CSRFToken': 'TyTJwjuEC7VV7mOqZ622haRaaUr0x0Ng4nrwSRFKQs7vdoBcJlK9qjAS69ghzhFu',
'Authorization': f'Token {quant_auth_key}'}
r = requests.get(url, headers=headers)
df = df = pd.read_json(r.content)
df.head()

        Date Ticker  Views  pct_change_week  pct_change_month
0 2016-10-17     FB    259       -29.343629        -30.888031
1 2016-10-24     FB    183       -29.343629        -30.888031
2 2016-10-31     FB    205        12.021858        -30.888031
3 2016-11-07     FB    180       -12.195122        -30.888031
4 2016-11-14     FB    179        -0.555556        -30.888031

## Using QuiverQuant Library to Access Data

In [9]:
#https://github.com/Quiver-Quantitative/python-api
token = quant_auth_key
quiver = quiverquant.quiver(token)

## Facebook - Data Exploration

#### WallStreetBets Data (Historical Daily)

In [10]:
quiver.wallstreetbets(ticker ='FB').head()

https://api.quiverquant.com/beta/historical/wallstreetbets/FB

        Date Ticker  Mentions  Rank  Sentiment
0 2018-08-01     FB         4     8  -0.054825
1 2018-08-02     FB        10     6   0.299040
2 2018-08-03     FB        10     5   0.005050
3 2018-08-06     FB        19     2   0.225889
4 2018-08-07     FB        13     5  -0.198246

#### Twitter Data (Historical Daily)

In [32]:
quiver.twitter(ticker='FB').tail()

,Date,Ticker,Followers,pct_change_day,pct_change_week,pct_change_month
468,2020-05-07,FB,13464234,-0.003921,-0.001255,0.008557
469,2020-05-06,FB,13464762,-0.007976,0.010473,-0.065120
470,2020-05-05,FB,13465836,-0.010819,0.015531,-0.113410
471,2020-05-03,FB,13467293,0.002042,0.027883,-0.176472
472,2020-05-02,FB,13467018,0.006579,0.027705,-0.205672

#### Wikipedia Pageviews (Historical Weekly)

In [11]:
quiver.wikipedia(ticker='FB').head()

         Date Ticker  Views  pct_change_week  pct_change_month
0  2016-10-17     FB  259.0       -29.343629        -30.888031
1  2016-10-24     FB  183.0       -29.343629        -30.888031
2  2016-10-31     FB  205.0        12.021858        -30.888031
3  2016-11-07     FB  180.0       -12.195122        -30.888031
4  2016-11-14     FB  179.0        -0.555556        -30.888031

#### Institutional Holdings (Historical)

In [51]:
quiver.sec13F(ticker='FB', owner= 'Dakota Wealth Management')

Pulling data from:  https://api.quiverquant.com/beta/live/sec13f?ticker=FB&owner=Dakota Wealth Management

,Date,ReportPeriod,Name,Ticker,Fund,Class,SH/PRN,Put/Call,Discretion,Value,Shares
0,2020-11-04,2020-09-30,FACEBOOK INC,FB,Dakota Wealth Management,CL A,SH,,OTR,680,2598
1,2020-11-04,2020-09-30,FACEBOOK INC,FB,Dakota Wealth Management,CL A,SH,,SOLE,4601,17567
2,2021-02-12,2020-12-31,FACEBOOK INC,FB,Dakota Wealth Management,CL A,SH,,OTR,703,2573
3,2021-02-12,2020-12-31,FACEBOOK INC,FB,Dakota Wealth Management,CL A,SH,,SOLE,5982,21901
4,2021-05-10,2021-03-31,FACEBOOK INC,FB,Dakota Wealth Management,CL A,SH,,OTR,756,2567
5,2021-05-10,2021-03-31,FACEBOOK INC,FB,Dakota Wealth Management,CL A,SH,,SOLE,10410,35344
6,2021-08-02,2021-06-30,FACEBOOK INC,FB,Dakota Wealth Management,CL A,SH,,OTR,890,2559
7,2021-08-02,2021-06-30,FACEBOOK INC,FB,Dakota Wealth Management,CL A,SH,,SOLE,13775,39616
8,2021-11-15,2021-09-30,FACEBOOK INC,FB,Dakota Wealth Management,CL A,SH,,OTR,981,2891
9,2021-11-15,2021-09-30,FACEBOOK INC,FB,Dakota Wealth Management,CL A,SH,,SOLE,14098,41540

#### Congress Trading (Historical)

In [55]:
quiver.congress_trading(ticker='FB', politician=False).tail()

,ReportDate,TransactionDate,Ticker,Representative,Transaction,Amount,House,Range
146,2016-04-28,2016-04-28,FB,Pat Roberts,Purchase,1001.0,Senate,"$1,001 - $15,000"
147,2016-04-04,2016-03-24,FB,Sheldon Whitehouse,Purchase,1001.0,Senate,"$1,001 - $15,000"
148,2016-03-25,2016-03-07,FB,John Hoeven,Purchase,50001.0,Senate,"$50,001 - $100,000"
149,2016-02-23,2016-02-16,FB,Sheldon Whitehouse,Purchase,1001.0,Senate,"$1,001 - $15,000"
150,2016-02-23,2016-01-28,FB,Sheldon Whitehouse,Purchase,1001.0,Senate,"$1,001 - $15,000"

#### OTC Short Percentages (Historical)

In [7]:
quiver.offexchange(ticker='FB').head()

        Date Ticker  OTC_Short  OTC_Total       DPI
0 2021-12-06     FB    3973440    7188049  0.552784
1 2021-12-03     FB    3934124   10969277  0.358649
2 2021-12-02     FB    3338402    8805530  0.379126
3 2021-12-01     FB    4431530   10666679  0.415455
4 2021-11-30     FB    3763576    8687228  0.433231